SPHINX_PROJECT_NAME=xSOFTip FOC Motor Control PWM Library
VERSION=1.0
DOXYGEN_DIRS=../../../sc_pwm/module_pwm_foc
SOURCE_INCLUDE_DIRS=../../../sc_pwm
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
