all: html

SPHINX_PROJECT_NAME = Pulse Width Modulation (PWM) Test Harness Application Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../../app_test_pwm/src
XDOC_DIR ?= ../../../../xdoc
include $(XDOC_DIR)/Makefile.inc
